const express = require("express")
const dotEnv = require("dotenv")
const vendorRoutes = require("./routes/vendorRoutes")
const firmRoutes = require("./routes/firmRoutes")
const productRoutes = require("./routes/productRoutes")
const bodyParser = require("body-parser")
const cors = require("cors")
const path = require("path")
const mongoose = require("mongoose")
const app = express()
app.use(cors())
const PORT = process.env.PORT || 4000;
dotEnv.config()
mongoose.connect(process.env.MONGO_URI).then(_=>console.log("DB connected"))
app.use(bodyParser.json())

app.use("/vendor",vendorRoutes)
app.use("/firm",firmRoutes)
app.use("/product",productRoutes)
app.use("/uploads",express.static('uploads'))

app.listen(PORT,_=>console.log(`server started at ${PORT}`))